[package]
name = "burn-mm"
version = "0.1.0"
edition = "2024"

[dependencies]
burn = { version = "0.19", features = ["autotune"]}

[features]
cpu = ["burn/cpu"]
cuda = ["burn/cuda"]
libtorch-cpu = ["burn/tch"]
libtorch-cuda = ["burn/tch"]
ndarray = ["burn/ndarray"]
openblas = ["ndarray", "burn/openblas"]
rocm = ["burn/rocm"]
vulkan = ["burn/vulkan"]
wgpu = ["burn/wgpu"]

default = ["ndarray"]
